LICENSE_DATABASE = {
    "MIT": {
        "name": "MIT License",
        "spdx_id": "MIT",
        "permissions": ["commercial_use", "modifications", "distribution", "private_use"],
        "conditions": ["include_copyright"],
        "limitations": ["no_liability"],
        "description": "A permissive license that allows users to do anything with the code with no restrictions except including copyright notice.",
        "compatibility": ["GPL-compatible", "MIT", "BSD", "Apache-2.0", "ISC"],
        "osi_approved": True,
        "fsf_free": True,
    },
    "Apache-2.0": {
        "name": "Apache License 2.0",
        "spdx_id": "Apache-2.0",
        "permissions": ["commercial_use", "modifications", "distribution", "private_use", "patent_use"],
        "conditions": ["include_notice", "state_changes"],
        "limitations": ["no_liability"],
        "description": "A permissive license that provides express grant of patent rights from contributors, plus a NOTICE file for attribution.",
        "compatibility": ["GPL-compatible", "MIT", "BSD", "Apache-2.0", "ISC", "LGPL"],
        "osi_approved": True,
        "fsf_free": True,
    },
    "GPL-2.0": {
        "name": "GNU General Public License v2.0",
        "spdx_id": "GPL-2.0",
        "permissions": ["commercial_use", "modifications", "distribution"],
        "conditions": ["disclose_source", "same_license", "state_changes"],
        "limitations": ["no_liability", "no_warranty"],
        "description": "Copyleft license requiring derivative works to be distributed under same license terms.",
        "compatibility": ["GPL-compatible"],
        "osi_approved": True,
        "fsf_free": True,
    },
    "GPL-3.0": {
        "name": "GNU General Public License v3.0",
        "spdx_id": "GPL-3.0",
        "permissions": ["commercial_use", "modifications", "distribution", "patent_use"],
        "conditions": ["disclose_source", "same_license", "state_changes"],
        "limitations": ["no_liability", "no_warranty"],
        "description": "Updated GPL version with clearer patent permissions, incompatible with proprietary code.",
        "compatibility": ["GPL-compatible"],
        "osi_approved": True,
        "fsf_free": True,
    },
    "LGPL-2.1": {
        "name": "GNU Lesser General Public License v2.1",
        "spdx_id": "LGPL-2.1",
        "permissions": ["commercial_use", "modifications", "distribution"],
        "conditions": ["disclose_source", "linking_exception", "state_changes"],
        "limitations": ["no_liability", "no_warranty"],
        "description": "Lesser GPL allows linking with non-GPL modules. More permissive than GPL.",
        "compatibility": ["GPL-compatible"],
        "osi_approved": True,
        "fsf_free": True,
    },
    "LGPL-3.0": {
        "name": "GNU Lesser General Public License v3.0",
        "spdx_id": "LGPL-3.0",
        "permissions": ["commercial_use", "modifications", "distribution", "patent_use"],
        "conditions": ["disclose_source", "linking_exception", "state_changes"],
        "limitations": ["no_liability", "no_warranty"],
        "description": "LGPL v3 with additional patent grant provisions.",
        "compatibility": ["GPL-compatible"],
        "osi_approved": True,
        "fsf_free": True,
    },
    "AGPL-3.0": {
        "name": "GNU Affero General Public License v3.0",
        "spdx_id": "AGPL-3.0",
        "permissions": ["commercial_use", "modifications", "distribution"],
        "conditions": ["disclose_source", "same_license", "source_on_network_use", "state_changes"],
        "limitations": ["no_liability", "no_warranty"],
        "description": "Strongest copyleft license - requires source available even when used over a network.",
        "compatibility": ["GPL-compatible"],
        "osi_approved": True,
        "fsf_free": True,
    },
    "BSD-2-Clause": {
        "name": "BSD 2-Clause Simplified License",
        "spdx_id": "BSD-2-Clause",
        "permissions": ["commercial_use", "modifications", "distribution", "private_use"],
        "conditions": ["include_copyright"],
        "limitations": ["no_liability"],
        "description": "Simplified BSD license with simplified terms, no advertising clause.",
        "compatibility": ["GPL-compatible", "MIT", "BSD", "Apache-2.0", "ISC"],
        "osi_approved": True,
        "fsf_free": True,
    },
    "BSD-3-Clause": {
        "name": "BSD 3-Clause New or Revised License",
        "spdx_id": "BSD-3-Clause",
        "permissions": ["commercial_use", "modifications", "distribution", "private_use"],
        "conditions": ["include_copyright", "no_endorsement"],
        "limitations": ["no_liability"],
        "description": "BSD license with explicit prohibition on use for endorsement.",
        "compatibility": ["GPL-compatible", "MIT", "BSD", "Apache-2.0", "ISC"],
        "osi_approved": True,
        "fsf_free": True,
    },
    "MPL-2.0": {
        "name": "Mozilla Public License 2.0",
        "spdx_id": "MPL-2.0",
        "permissions": ["commercial_use", "modifications", "distribution", "private_use"],
        "conditions": ["include_license", "disclose_modifications"],
        "limitations": ["no_liability", "no_warranty"],
        "description": "Mozilla's license - weak copyleft with file-level rather than project-level linking.",
        "compatibility": ["GPL-compatible", "MIT", "BSD", "Apache-2.0", "ISC", "LGPL"],
        "osi_approved": True,
        "fsf_free": True,
    },
    "ISC": {
        "name": "ISC License",
        "spdx_id": "ISC",
        "permissions": ["commercial_use", "modifications", "distribution", "private_use"],
        "conditions": ["include_copyright"],
        "limitations": ["no_liability"],
        "description": "Simplified permissive license similar to MIT but with clearer language.",
        "compatibility": ["GPL-compatible", "MIT", "BSD", "Apache-2.0", "ISC"],
        "osi_approved": True,
        "fsf_free": True,
    },
    "Unlicense": {
        "name": "The Unlicense",
        "spdx_id": "Unlicense",
        "permissions": ["commercial_use", "modifications", "distribution", "private_use", "sublicense"],
        "conditions": [],
        "limitations": ["no_liability", "no_warranty"],
        "description": "Public domain equivalent - no conditions or restrictions.",
        "compatibility": ["GPL-compatible", "MIT", "BSD", "Apache-2.0", "ISC", "LGPL", "GPL", "MPL-2.0"],
        "osi_approved": True,
        "fsf_free": True,
    },
    "CC0-1.0": {
        "name": "Creative Commons Zero v1.0 Universal",
        "spdx_id": "CC0-1.0",
        "permissions": ["commercial_use", "modifications", "distribution", "private_use", "sublicense"],
        "conditions": [],
        "limitations": ["no_liability"],
        "description": "Public domain dedication - waives all copyright and related rights.",
        "compatibility": ["GPL-compatible", "MIT", "BSD", "Apache-2.0", "ISC", "LGPL", "GPL", "MPL-2.0"],
        "osi_approved": True,
        "fsf_free": True,
    },
    "Proprietary": {
        "name": "Proprietary License",
        "spdx_id": "Proprietary",
        "permissions": ["private_use"],
        "conditions": ["requires_explicit_permission"],
        "limitations": ["all_rights_reserved"],
        "description": "All rights reserved. Usage requires explicit permission from the owner.",
        "compatibility": [],
        "osi_approved": False,
        "fsf_free": False,
    },
}